name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Clippy & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Print Rust version
        run: rustc -vV

      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Tests
        run: cargo test --workspace
